# google-ads.properties - ???????? ????? ?? ????????
api.googleads.developerToken=pTtW_pCfhJ8AtIVOs_i28g
api.googleads.clientId=797055843332-kfua8ueucii9nmt4f1ads8452qrau124.apps.googleusercontent.com
api.googleads.clientSecret=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
api.googleads.refreshToken=1//03ImE2bogbe6PCgYIARAAGAMSNwF-L9Ir7XC6KlkrVV_p0Jf1FhTWuZhLQINgRV_RKRqyRRtxu2AxSol7poqc42BbKwN3JjeHA7I
api.googleads.loginCustomerId=3458720615