# google-ads.properties - ???????? ????? ?? ????????
api.googleads.developerToken=pTtW_pCfhJ8AtIVOs_i28g
api.googleads.clientId=797055843332-fg61agga3ej70b3b74cn8s8veker1n57.apps.googleusercontent.com
api.googleads.clientSecret=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
api.googleads.refreshToken=1//03lbVHjAZQHEVCgYIARAAGAMSNwF-L9IrCqcNYwpNHCNlS1vlGBuKnAiq6woKYQrSKiAVHuvvjLUAczA5ZATLQ-5I9KMJc2qLvFs
api.googleads.loginCustomerId=3458720615