# google-ads.properties - ???????? ????? ?? ????????
api.googleads.developerToken=pTtW_pCfhJ8AtIVOs_i28g
api.googleads.clientId=797055843332-kfua8ueucii9nmt4f1ads8452qrau124.apps.googleusercontent.com
api.googleads.clientSecret=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
api.googleads.refreshToken=1//03J-Yp22hIMtGCgYIARAAGAMSNwF-L9IrTViAbBKTXHwoFG54OJg8g--yupYUHB1rwAd9Yln80i2o59mLgxv4U5F9wdscRDavOCw
api.googleads.loginCustomerId=3458720615